In [16]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error,r2_score

In [17]:
df = pd.read_csv(r'DataExtract.csv')

In [18]:
df.head()

subjectedLane  uTurnVehicleType  opposingVehicleType   speed  distance  \
0              0                 0                    2   3.600     15.60   
1              1                 2                    3   3.756      9.35   
2              0                 1                    2   3.527     16.45   
3              0                 3                    2  10.270     15.10   
4              0                 1                    2   8.800     11.49   

   actualTime     delay  
0       4.720  2.638334  
1       4.640  3.062232  
2       6.400  4.240366  
3       5.920  4.707440  
4       1.371  0.065318

In [19]:
df.describe()

subjectedLane  uTurnVehicleType  opposingVehicleType       speed  \
count     120.000000        120.000000            120.00000  120.000000   
mean        0.166667          1.541667              1.95000    6.545492   
std         0.374241          0.684717              0.76532    3.324574   
min         0.000000          0.000000              0.00000    0.500000   
25%         0.000000          1.000000              2.00000    4.574000   
50%         0.000000          2.000000              2.00000    5.806500   
75%         0.000000          2.000000              2.00000    8.400000   
max         1.000000          3.000000              3.00000   16.700000   

         distance  actualTime       delay  
count  120.000000  120.000000  120.000000  
mean    21.122425    5.050100    2.081150  
std     12.038717    3.024192    2.269616  
min      0.890000    0.080000   -0.425219  
25%     12.907500    2.790000    0.326887  
50%     19.120000    4.354000    1.303981  
75%     27.567500    6.445500    2.987885  
max     56.400000   13.720000   10.545000

In [20]:
#Splitting the data into independent and dependent variables
X = df.iloc[:,0:6].values
y = df.iloc[:,6:7].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y)

The independent features set: 
[[ 0.     0.     2.     3.6   15.6    4.72 ]
 [ 1.     2.     3.     3.756  9.35   4.64 ]
 [ 0.     1.     2.     3.527 16.45   6.4  ]
 [ 0.     3.     2.    10.27  15.1    5.92 ]
 [ 0.     1.     2.     8.8   11.49   1.371]]
The dependent variable: 
[[ 2.63833400e+00]
 [ 3.06223247e+00]
 [ 4.24036568e+00]
 [ 4.70743996e+00]
 [ 6.53181818e-02]
 [ 1.40833333e+00]
 [ 1.40833333e+00]
 [ 2.24911534e-01]
 [ 4.62379310e+00]
 [ 8.69230769e-02]
 [ 4.03644518e+00]
 [ 1.45680851e+00]
 [ 1.75000000e+00]
 [ 2.11110180e+00]
 [ 2.11110180e+00]
 [ 9.63724138e+00]
 [ 9.63724138e+00]
 [ 1.19174603e+00]
 [ 1.05450000e+01]
 [ 2.03703704e-02]
 [ 8.80980392e-01]
 [ 2.39835821e+00]
 [ 2.39835821e+00]
 [ 1.23086023e+00]
 [ 3.38960275e-01]
 [ 7.34516129e-01]
 [ 1.02323184e+00]
 [ 5.52615385e+00]
 [ 5.52615385e+00]
 [ 2.52111111e+00]
 [ 9.84090909e-02]
 [ 2.34117647e-01]
 [ 4.84352941e+00]
 [ 4.84352941e+00]
 [ 1.79692308e+00]
 [ 1.79692308e+00]
 [ 2.96888889e+00]
 [ 2.96888889e+

In [21]:
#split the dataframe into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=9)

In [22]:
lin_reg_mod = LinearRegression()

In [23]:
#fit the model on the training data:
lin_reg_mod.fit(X_train, y_train)
print('Intercept: \n', lin_reg_mod.intercept_)
print('Coefficients: \n', lin_reg_mod.coef_)

Intercept: 
 [-1.3155179]
Coefficients: 
 [[ 0.15522062 -0.02002757  0.07757852  0.14542614 -0.08934428  0.82839033]]


In [24]:
pred = lin_reg_mod.predict(X_test)

In [25]:
pred

array([[ 2.42256536],
       [ 3.82805497],
       [ 7.14003709],
       [ 4.3308753 ],
       [ 4.31989333],
       [ 0.41522524],
       [ 2.39765851],
       [ 4.23058272],
       [ 0.2098092 ],
       [ 0.49935266],
       [ 3.03759583],
       [ 0.21430118],
       [ 1.04413429],
       [-0.05786469],
       [ 2.28484456],
       [ 1.96743634],
       [ 1.70435838],
       [ 3.00216948],
       [ 0.48114194],
       [ 0.73720059],
       [ 2.08254475],
       [ 1.56820463],
       [ 2.21815539],
       [ 0.50648836]])

In [26]:
#check the predictions against the actual values by using the RMSE and R-2 metrics, two metrics commonly used to evaluate regression tasks
test_set_rmse = (np.sqrt(mean_squared_error(y_test, pred)))

test_set_r2 = r2_score(y_test, pred)

In [27]:
## Note that for rmse, the lower that value is, the better the fit
print(test_set_rmse)
# The closer towards 1, the better the fit
print(test_set_r2)

0.8193765168266206
0.7890172484258378


In [29]:
%%bash

pip install seaborn

Couldn't find program: 'bash'


In [1]:
#import numpy as np
#import seaborn as sns
#import matplotlib.pyplot as plt
#sns.set_theme(color_codes=True)
#sns.regplot(x="speed", y="delay", data=df);
